name: sample_env
channels:
dependencies:
  - python=3.7
  - pip=22.1.2
  - pip:
    - streamlit==0.88.0
    - numpy==1.21.0
    - pandas==1.3.2
    - nltk==3.6.2
    - scikit-learn==0.24.1
    - wordcloud==1.8.1
    - PyDictionary==2.0.1
    - matplotlib==3.4.3
    - openpyxl==3.0.9
 
